### PR TITLE
Asl: Cumulative changes

### PR DESCRIPTION
**Pull request by deadw00d**
Implementation of Prefs/Asl
Loading of preference in asl.library
Porting code changes from MorphOS code releases

Build-tested under linux-x86_64

### CODE REVIEW

**Comment by mattrust** [comment]
We have the cd/ct files in a submodule. Would you please remove "Remove unused strings. Synchronize .ct files with .cd file" remove from this pull request?

This is the  repository for the cd/ct files of ASL.
https://github.com/aros-translation-team/asl.library
It would save me a lot of hassle if you create there a pull request.

**Comment by mattrust** [comment]
Oops, it's prefs/asl. So it means we need a new repository for the catalogs files of prefs/asl.

**Comment by deadw00d** [comment]
Ok, I will rebuild the PR so that it does not include catalogs. Can you point me to repository where I should put catalogs?

**Comment by deadw00d** [comment]
I pushed branch with removed catalogs directory. Note that it will fail to build now. You need to provide catalogs - attached.
[catalogs.zip](https://github.com/aros-development-team/AROS/files/10318065/catalogs.zip)

**Comment by mattrust** [comment]
Cheers!

grafik

**Comment by deadw00d** [comment]
Great, thanks for merging :)

**Pull request merged**
